In [45]:
import numpy as np

## Задача 1

In [46]:
# Объявляем матрицы

A = np.matrix([[1, 2, 1],
               [-2, 1, 1]])

B = np.matrix([[3, 1],
               [-1, 0],
               [2, 4]])

C = np.matrix([[-2, 2],
               [1, -1],
               [1, 2]])

In [47]:
# Копирование и преобразование матриц

# Добавить строку с нулями в конец
AA = np.insert(A, 2, 0, axis=0).copy()
print(AA)

# Добавить столбец с нулями в конец
BB = np.insert(B, 2, 0, axis=1).copy()
print(BB)

[[ 1  2  1]
 [-2  1  1]
 [ 0  0  0]]
[[ 3  1  0]
 [-1  0  0]
 [ 2  4  0]]


In [48]:
# Математические операции над матрицами

# Преобразованные копии матрицы (уравнивание размерности)
matrixResult1 = AA + 2 * BB
print(matrixResult1)

# Оригиналы матриц
matrixResult2 = B + 2 * C
print(matrixResult2)

[[ 7  4  1]
 [-4  1  1]
 [ 4  8  0]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [49]:
# Решение первой математической операции с помощью транспонирование матрицы
AAA = np.transpose(A).copy()
print(AAA)

# Решение
matrixResult1 = AAA + 2 * B
print(matrixResult1)

[[ 1 -2]
 [ 2  1]
 [ 1  1]]
[[7 0]
 [0 1]
 [5 9]]


## Задача 2

In [50]:
# Создание матрицы 8х8, заполненное нулями
zero = np.zeros((8, 8))
print(zero)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [51]:
# Заполнение матрицы единицами в шахматном порядке
zero[0::2, 1::2] = 1
zero[1::2, 0::2] = 1
print(zero)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Задача 3

In [52]:
# Формирование векторов

# Вектор с шагом 0.1
vec1 = np.arange(start=0, stop=1.5, step=0.1, dtype='float')
print(vec1)
print(vec1.shape) # Длинна многомерного массива
print(vec1.size) # Размерность

# Другой способ
gen_sequence1, step1 = np.linspace(0, 1.5, num=15, dtype='float', retstep=True)
print(gen_sequence1)
print(gen_sequence1.shape) # Длинна многомерного массива
print(gen_sequence1.size) # Размерность
print(step1) # Шаг

# Вектор с шагом 1
vec2 = np.arange(start=1, stop=7, step=1, dtype='int64')
print(vec2)
print(vec2.shape) # Длинна многомерного массива
print(vec2.size) # Размерность

# Другой способ
gen_sequence2, step2 = np.linspace(1, 6, num=6, dtype='int64', retstep=True)
print(gen_sequence2)
print(gen_sequence2.shape) # Длинна многомерного массива
print(gen_sequence2.size) # Размерность
print(step2) # Шаг

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
(15,)
15
[0.         0.10714286 0.21428571 0.32142857 0.42857143 0.53571429
 0.64285714 0.75       0.85714286 0.96428571 1.07142857 1.17857143
 1.28571429 1.39285714 1.5       ]
(15,)
15
0.10714285714285714
[1 2 3 4 5 6]
(6,)
6
[1 2 3 4 5 6]
(6,)
6
1.0


In [53]:
# Преобразование вектора в матрицу 5х3
vec1 = vec1.reshape(5, 3)
print(vec1)

# Преобразование вектора в матрицу 3х2
vec2 = vec2.reshape(3, 2)
print(vec2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [54]:
# Перемножение матриц
vec1.dot(vec2)
np.matmul(vec1, vec2)

# Приводим матрицы к одной форме (Broadcasting)
vec2copy = np.insert(vec2, 3, 0, axis=0).copy()
vec2copy = np.insert(vec2copy, 4, 0, axis=0)
vec2copy = np.insert(vec2copy, 2, 0, axis=1)
print(vec2copy)

# Перемножение матриц
vec3 = vec1 * vec2copy
print(vec3)

[[1 2 0]
 [3 4 0]
 [5 6 0]
 [0 0 0]
 [0 0 0]]
[[0.  0.2 0. ]
 [0.9 1.6 0. ]
 [3.  4.2 0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]]


## Задача 4

In [55]:
# Формирование вектора из целых чисел
vec = np.arange(start=1, stop=37, step=2, dtype='int32')
print(vec)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]


In [56]:
# Элементы кратные 3
result = vec[vec % 3 == 0]
print(result)

# Bool обображение в матрице по условию
vec % 3 == 0

[ 3  9 15 21 27 33]


array([False,  True, False, False,  True, False, False,  True, False,
       False,  True, False, False,  True, False, False,  True, False])