In [1]:
import numpy as np

## Задача 1

In [52]:
# Объявляем матрицы

A = np.matrix([[1, 2, 1],
               [-2, 1, 1]])

B = np.matrix([[3, 1],
               [-1, 0],
               [2, 4]])

C = np.matrix([[-2, 2],
               [1, -1],
               [1, 2]])

In [53]:
# Копирование и преобразование матриц

# Добавить строку с нулями в конец
AA = np.insert(A, 2, 0, axis=0).copy()
print(AA)

# Добавить столбец с нулями в конец
BB = np.insert(B, 2, 0, axis=1).copy()
print(BB)

[[ 1  2  1]
 [-2  1  1]
 [ 0  0  0]]
[[ 3  1  0]
 [-1  0  0]
 [ 2  4  0]]


In [54]:
# Математические операции над матрицами

# Преобразованные копии матрицы (уравнивание размерности)
matrixResult1 = AA + 2 * BB
print(matrixResult1)

# Оригиналы матриц
matrixResult2 = B + 2 * C
print(matrixResult2)

[[ 7  4  1]
 [-4  1  1]
 [ 4  8  0]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [87]:
# Решение первой математической операции с помощью транспонирование матрицы
AAA = np.transpose(A).copy()
print(AAA)

# Решение
matrixResult1 = AAA + 2 * B
print(matrixResult1)

[[ 1 -2]
 [ 2  1]
 [ 1  1]]
[[7 0]
 [0 1]
 [5 9]]


## Задача 2

In [75]:
# Создание матрицы 8х8, заполненное нулями
zero = np.zeros((8, 8))
print(zero)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [76]:
# Заполнение матрицы единицами в шахматном порядке
zero[0::2, 1::2] = 1
zero[1::2, 0::2] = 1
print(zero)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


## Задача 3

In [82]:
# Формирование векторов

# Вектор с шагом 0.1
vec1 = np.arange(start=0, stop=1.5, step=0.1, dtype='float')
print(vec1)

# Вектор с шагом 1
vec2 = np.arange(start=1, stop=7, step=1, dtype='int64')
print(vec2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1 2 3 4 5 6]


In [110]:
# Преобразование вектора в матрицу 5х3
vec1 = vec1.reshape(5, 3)
print(vec1)

# Преобразование вектора в матрицу 3х2
vec2 = vec2.reshape(3, 2)
print(vec2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [113]:
# Приводим матрицы к одной форме (Broadcasting)
vec2copy = np.insert(vec2, 3, 0, axis=0).copy()
vec2copy = np.insert(vec2copy, 4, 0, axis=0)
vec2copy = np.insert(vec2copy, 2, 0, axis=1)
print(vec2copy)

# Перемножение матриц
vec3 = vec1 * vec2copy
print(vec3)

[[1 2 0]
 [3 4 0]
 [5 6 0]
 [0 0 0]
 [0 0 0]]
[[0.  0.2 0. ]
 [0.9 1.6 0. ]
 [3.  4.2 0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]]


## Задача 4

In [116]:
# Формирование вектора из целых чисел
vec = np.arange(start=1, stop=37, step=2, dtype='int32')
print(vec)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35]


In [125]:
# Элементы кратные 3
result = vec[(vec % 3 == 0)]
print(result)

[ 3  9 15 21 27 33]
